version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME:?DB_NAME is required}
      - DB_USER=${DB_USER:?DB_USER is required}
      - DB_PASS=${DB_PASS:?DB_PASS is required}
      - SECRET_KEY=${DJANGO_SECRET_KEY:?DJANGO_SECRET_KEY is required}
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:18-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_NAME:?DB_NAME is required}
      - POSTGRES_USER=${DB_USER:?DB_USER is required}
      - POSTGRES_PASSWORD=${DB_PASS:?DB_PASS is required}

volumes:
  dev-db-data:
  dev-static-data:
